### ISSUE TITLE
And it's black screen

### ISSUE THREAD

**Issue by TrustTheBoy** [react-native-china/react-native-webkit-webview#2]

**Comment by Obooman** [comment]
Hi, any platform and configuration info? android version,emulator or real device,and react-native version.

**Comment by TrustTheBoy** [comment]
Sorry,I'm using the genymotion simulator, react native:0.50.4 and 0.49.2,At present, all devices appear black screen

**Comment by Obooman** [comment]
Then have you follow all steps in README?
It seems that there are some errors in the android-building.check whether Gradle builds or other step cause errors and feel free to paste it here.

**Comment by TrustTheBoy** [comment]
@Obooman  Yes, I follow the README operation, the content area or the black screen

**Comment by Obooman** [comment]
Can you tell me more info about this?I have tested this project and it works well on my platform, you may offer me the android error log or react-native build service log, sorry but I can't tell any solution without more information.

**Comment by matsatit** [comment]
I also have that problems with RN: "0.50.4". Please check it. thanks

**Comment by matsatit** [comment]
Hi, sr for my mistake, add style with flex :1, will resolve this

**Comment by Obooman** [comment]
good job @matsatit  cc @TrustTheBoy is this also your problem?

**Comment by Obooman** [comment]
I'm going to close this issue, feel free to reopen it if this issue still exists.
