### ISSUE TITLE
Can't install package getting the following error

### ISSUE THREAD

**Issue by isAlmogK** [react-native-china/react-native-webkit-webview#3]
npm ERR! argv "/Users/Almog/.nvm/versions/node/v6.9.5/bin/node" "/Users/Almog/.nvm/versions/node/v6.9.5/bin/npm" "install" "react-native-webkit-webview" "--save"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! react-native-webkit-webview@0.10.6 postinstall: `node get_library.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-native-webkit-webview@0.10.6 postinstall script 'node get_library.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-native-webkit-webview package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node get_library.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-native-webkit-webview
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-native-webkit-webview
npm ERR! There is likely additional logging output above.

**Comment by Obooman** [comment]
update your node may solve your issue

**Comment by dotansimha** [comment]
Same here. Tried with Node 8 and 9.

**Comment by vieraleonel** [comment]
Same here Node 8.9.2 and npm 5.5.1

**Comment by vieraleonel** [comment]
Solved the problem creating "libs" directory while file was downloading (during install)

`mkdir node_modules/react-native-webkit-webview/libs`

Maybe you should add "libs" dir with a .gitkeep to solve it.

**Comment by Obooman** [comment]
sorry for my late response, I forget to check the folder existence before move file to /lib, keeping a .gitkeep file seems a resonable solution, a bug-fixed version will soon be released.

**Comment by Obooman** [comment]
```bash
yarn add react-native-webkit-webview@0.10.7
```
or
```
npm i --save react-native-webkit-webview@0.10.7
```
